import { z } from 'zod';
import { gonkaChatJson, gonkaConfigured } from './gonka.js';
import type { Analysis, Source } from './types.js';

const Schema = z.object({
  sentiment: z.enum(['bullish', 'bearish', 'neutral', 'mixed']),
  confidence: z.number(), // 0..1
  risk: z.enum(['low', 'medium', 'high']),
  keyDevelopments: z.array(z.string()),
  risks: z.array(z.string()),
});

const SYSTEM = [
  'You are a market-intelligence analyst. From the briefing only, extract: overall sentiment,',
  'a calibrated confidence (0..1), overall risk, the key developments, and the main risks.',
  'Do not invent facts not in the briefing. No investment advice.',
  'Respond with a JSON object:',
  '{ "sentiment": "bullish|bearish|neutral|mixed", "confidence": 0..1,',
  '  "risk": "low|medium|high", "keyDevelopments": [..], "risks": [..] }',
].join(' ');

const FALLBACK: Analysis = {
  sentiment: 'mixed',
  confidence: 0.5,
  risk: 'medium',
  keyDevelopments: ['Demo mode - set GONKA_API_KEY for a real analysis.'],
  risks: ['Analysis not generated by a model in demo mode.'],
};

/**
 * Turns the research briefing into structured sentiment / confidence / risk /
 * key points. Grounded strictly in the briefing.
 */
export async function analyze(
  question: string,
  findings: string,
  sources: Source[],
): Promise<Analysis> {
  if (!gonkaConfigured()) return FALLBACK;

  const user = [
    `Question: ${question}`,
    '',
    'Briefing:',
    findings,
    '',
    'Sources:',
    sources.map((s) => `- ${s.publisher}: ${s.title}`).join('\n'),
  ].join('\n');

  const parsed = await gonkaChatJson<Analysis>({ system: SYSTEM, user });
  try {
    if (!parsed) throw new Error('no parseable JSON');
    return Schema.parse(parsed);
  } catch {
    return FALLBACK;
  }
}
