[package]
name = "blockchain"
edition = "2024"
# If your Sui toolchain rejects `edition = "2024"`, use "2024.beta" instead.

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
blockchain = "0x0"

[dev-dependencies]

[dev-addresses]
